---
# DO NOT TOUCH
version: 1

# Item
# "ID:META:SLOT:NAME"
item: "345:0:4:§fServers"

# Form
title: "Servers"
content: "Choose your server:"
servers:
  Lobby:
    ip: "rutelia-mc.fr:19132"
    form: "§7- §fRutélia §f-"
  KitMap:
    ip: "rutelia-mc.fr:19135"
    form: "§7- §fKitMap §f-"

# Events
op: true

food: false
break: false
place: false
fly: true
use: true
...
